import Header from '@/components/Header';
import './globals.css';

export const metadata = {
  title: 'IMDB Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <Header />
        {/*Navbar*/}
        {/*SearchBox*/}

        {children}
      </body>
    </html>
  )
}
